server:
  port: 8080

spring:
  application:
    name: generic-etl
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

etl:
  api-keys: sk-admin:ADMIN,sk-operator:OPERATOR,sk-viewer:VIEWER

# ── Apache Camel ──
camel:
  springboot:
    main-run-controller: true
    name: GenericETL
    jmx-enabled: true
  component:
    kafka:
      enabled: false
    ftp:
      enabled: false

# ── Hawtio Management Console ──
hawtio:
  authenticationEnabled: false
  proxyWhitelist: localhost
