-- ============================================================
-- Dev H2 Schema — sample tables for ETL pipeline testing
-- ============================================================

CREATE TABLE IF NOT EXISTS employees (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id      BIGINT,
    name        VARCHAR(100),
    emp_name    VARCHAR(100),
    dept        VARCHAR(50),
    dept_code   VARCHAR(50),
    salary      DECIMAL(12, 2),
    salary_amt  DECIMAL(12, 2),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    hire_dt     DATE DEFAULT '2022-01-01'
);

CREATE TABLE IF NOT EXISTS orders (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  BIGINT,
    amount       DECIMAL(12, 2),
    status       VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS customers (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   VARCHAR(100),
    tier   VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS trade_history (
    trade_date DATE,
    amount     DECIMAL(14, 2)
);

CREATE TABLE IF NOT EXISTS trades_today (
    trade_date DATE,
    amount     DECIMAL(14, 2)
);

-- ============================================================
-- Sample data
-- ============================================================
INSERT INTO employees (emp_id, emp_name, dept_code, salary_amt, hire_dt, name, dept, salary, created_at) VALUES
    (1, 'Alice',   'ENG',  8000, '2021-03-15', 'Alice',   'ENG',  8000, '2024-01-15 09:00:00'),
    (2, 'Bob',     'ENG',  6000, '2022-07-01', 'Bob',     'ENG',  6000, '2024-02-20 10:30:00'),
    (3, 'Charlie', 'SALES', 5500, '2023-01-10', 'Charlie', 'SALES', 5500, '2024-03-10 14:00:00'),
    (4, 'Diana',   'SALES', 4500, '2023-06-20', 'Diana',   'SALES', 4500, '2024-04-01 08:00:00'),
    (5, 'Eve',     'HR',    7000, '2020-11-01', 'Eve',     'HR',    7000, '2024-05-01 09:00:00');

INSERT INTO orders (id, customer_id, amount, status) VALUES
    (1, 1, 150.00, 'completed'),
    (2, 2, 200.00, 'completed'),
    (3, 1,  50.00, 'pending'),
    (4, 3, 300.00, 'completed');

INSERT INTO customers (id, name, tier) VALUES
    (1, 'Acme Corp', 'Gold'),
    (2, 'Globex',    'Silver'),
    (3, 'Initech',   'Gold');

INSERT INTO trade_history (trade_date, amount) VALUES
    ('2024-01-01', 1000.00),
    ('2024-01-02', 1500.00),
    ('2024-01-03',  800.00);

INSERT INTO trades_today (trade_date, amount) VALUES
    (CURRENT_DATE, 500.00),
    (CURRENT_DATE, 300.00);
