# Minimal Camel route for testing CSV file input
- route:
    id: test-minimal
    from:
      uri: "file:data/in?fileName=input.csv&noop=true&idempotent=true"
      steps:
      - unmarshal:
          csv:
            use-maps: true
      - setProperty:
          name: pipelineName
          constant: test-minimal
      - to: bean:loadRouter
