dependencies {
    implementation project(':etl-common')
    implementation project(':etl-core')
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    // Camel connectors for SFTP/Kafka output
    implementation "org.apache.camel:camel-ftp:${camelVersion}"
    implementation "org.apache.camel:camel-kafka:${camelVersion}"
    implementation "org.apache.camel:camel-core:${camelVersion}"
    runtimeOnly 'org.postgresql:postgresql:42.7.4'
}
