dependencies {
    implementation project(':etl-common')
    implementation project(':etl-core')
    implementation 'org.springframework.boot:spring-boot-starter-jdbc:3.3.5'
    implementation 'org.springframework.boot:spring-boot-starter-web:3.3.5'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.2'
    runtimeOnly 'org.postgresql:postgresql:42.7.4'
}
